### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Chris-Prime** [Chris-Prime/xCrate#1]
- [ ] Write Crate & Key loading/saving
- [ ] Implement per key permissions
- [ ] Implement particle effects
- [ ] Create events
- [ ] Make Chest filling mechanism
- [ ] /addcrate
- [ ] /removecrate
- [ ] /editcrate
- [ ] /givekey

**Comment by akaSnapy** [comment]
Help needed?
